definitions:
  main.User:
    properties:
      age:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: Ini adalah dcontoh dokumentasi API
  title: Sample API
  version: "1.0"
paths:
  /users:
    get:
      description: Mendapatkan seluruh pengguna
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Mendapatkan daftar pengguna
      tags:
      - users
    post:
      consumes:
      - application/json
      description: This endpoint allows creating a new user with the provided details
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.User'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create a new user
      tags:
      - users
  /users/{id}:
    get:
      description: Get details for a specific user by their ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get user by ID
      tags:
      - users
swagger: "2.0"
