// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Support Team",
            "email": "ivandhitya@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "get": {
                "description": "Menghasilkan token JWT dengan klaim username, role, dan waktu kedaluwarsa (expiry) yang dapat digunakan untuk autentikasi pada endpoint yang dilindungi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Generate JWT Token",
                "responses": {
                    "200": {
                        "description": "token\" \"Token JWT berhasil dihasilkan",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "message\" \"Could not generate token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/salary": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ini adalah endpoint untuk mendapatkan data salary yang hanya bisa diakses dengan token JWT",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Secure"
                ],
                "summary": "Get Salary Data",
                "responses": {
                    "200": {
                        "description": "Data aman",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Token tidak valid atau tidak disediakan",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7777",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Contoh Auth API Menggunakan",
	Description:      "Ini adalah contoh implementasi autentikasi menggunakan Echo dan JWT.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
